# Generated by Django 3.1.4 on 2020-12-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tb_estoque',
            fields=[
                ('id_estoque', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id estoque')),
                ('id_produto', models.IntegerField(verbose_name='Id produto')),
                ('ds_n', models.CharField(max_length=45, verbose_name='Nome')),
                ('ds_tamanho', models.CharField(max_length=45, verbose_name='Tamanho')),
                ('ds_cor', models.CharField(max_length=45, verbose_name='Cor')),
                ('vl_preco_custo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Custo')),
                ('vl_preco_venda', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preco de venda')),
                ('tx_lucro', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxa de lucro')),
                ('dt_entrada', models.DateField(verbose_name='Data de entrada')),
            ],
        ),
    ]
